### ISSUE TITLE
Menu Navigaion RTL

### ISSUE THREAD

**Issue by shai-benshimol** [gurayyarar/AdminBSBMaterialDesign#10]
How can i move  the menu navigation to the right?

**Comment by Yousefjb** [comment]
Hi,  
you can check [my fork](https://github.com/Yousefjb/AdminBSBMaterialDesign) where i made a good rtl support. [A Demo](https://yousefjb.github.io/AdminBSBMaterialDesign) to see if it satisfy you.
All you have to do is to include this [css ](https://github.com/Yousefjb/AdminBSBMaterialDesign/blob/master/css/rtl.css) in your page heade.  
If you find an element doesn't work for you then replace all pull-right with pull-left in your page
