### ISSUE TITLE
Navbar collapse class

### ISSUE THREAD

**Issue by dheroefic** [gurayyarar/AdminBSBMaterialDesign#104]
Hey,

First of all thanks for this wonderful template, we used it for our latest project.
I would like to ask whether this template has class navbar collapsed so that i have much bigger space for content.
It seems it already have class lg-close lg-closed to minimize the navbar, but it doesnt have button to easily hide and show the navbar.

![capture](https://user-images.githubusercontent.com/25289400/34283296-8cb2ffa2-e6fd-11e7-81b4-28df1f616b79.JPG)

**Comment by azizrahaman** [comment]
I have the same issue, did you got any solution?

**Comment by dheroefic** [comment]
@azizrahaman No, unfortunately. I just move on not implementing that anymore.

**Comment by azizrahaman** [comment]
#16  solved this issues for me

**Comment by dheroefic** [comment]
@azizrahaman thank you 👍
