### ISSUE TITLE
@Html.CheckBoxFor MVC not showing well in card view

### ISSUE THREAD

**Issue by taimuralam** [gurayyarar/AdminBSBMaterialDesign#117]
I am trying to put the checkboxfor in the card view for the boolean values in my model but it is not showing up in the view. I tried overriding -webkit-appearance to None and also a few other things but it just doesnt seem to work.

Here is my code

`    public class License
    {
        [Key]
        public Guid LicenseId { get; set; }

        [Required]
        public string LicenseKey { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? FirstInstalledOn { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? LastInstalledOn { get; set; }

        public bool IsDEMO { get; set; }

        [ForeignKey("Product")]
        public Guid ProductId { get; set; }
        public virtual Product Product { get; set; }
}`

I have attached my view page
![viewpage](https://user-images.githubusercontent.com/26968659/37447335-b14bcb9c-2847-11e8-81cb-142bd9aed8d9.PNG)

Rendered View is like this:-

![renderedviewpage](https://user-images.githubusercontent.com/26968659/37447377-dc3066a6-2847-11e8-83ce-84bdc231494b.PNG)

I tried all this but it still doesn't shows the check box for strongly typed views. Although a normal input tag shows up well. 

I am new to front-end development so please pardon me for my noobie skills

**Comment by arysfan** [comment]
Hi there, I've same the same problem with you, but I'm using Web Forms, maybe this article can help : https://github.com/Dogfalo/materialize/issues/2463

**Comment by taimuralam** [comment]
Thanks Bro. But I fixed that way before. I don't really remember how but I do remember that it was fixed not by fiddling with id but something different than that. Anyway, thanks for your response. :)
