### ISSUE TITLE
admin.js:333 Uncaught TypeError: dropdown.size is not a function

### ISSUE THREAD

**Issue by zulClunk** [gurayyarar/AdminBSBMaterialDesign#12]
when click notification button and profile button :
- admin.js:333 Uncaught TypeError: dropdown.size is not a function
-after update JQuery v 3.1.1

**Comment by alirizaadiyahsi** [comment]
`size()` returns `length`. `size()` removed in **jquery version 3.0**

[JQuery API Reference: size()](https://api.jquery.com/size/)

[stackoverflow-jQuery size() method vs length attribute](http://stackoverflow.com/questions/2738352/jquery-size-method-vs-length-attribute)

So, if you want to use it with JQuery 3.x, you should change `if (dropdown.size() > 0)` with `if (dropdown.length > 0)`
