### ISSUE TITLE
No Efect Sidebar Menu.

### ISSUE THREAD

**Issue by wagnerfillio** [gurayyarar/AdminBSBMaterialDesign#122]
Is it possible to choose any menu, and keep the sidebar ineffective?

Example: Only content should change.

**Comment by thatal** [comment]
![Screenshot_2019-03-09 Welcome To Bootstrap Based Admin Template - Material Design](https://user-images.githubusercontent.com/17490342/54067660-90824800-4268-11e9-8aab-b52e136b33bb.png) I have made changes in style.css and admin.js and it works properly.
