### ISSUE TITLE
Error in label and form input

### ISSUE THREAD

**Issue by wagnerfillio** [gurayyarar/AdminBSBMaterialDesign#123]
Hello!
Can you help with this problem?
When using form-line, to add items, everything happens fine, but to edit, I have the following problems.

label of the form-line, mixes with the value of the input, and in the form-line there is a blue border, even if the focus is not in the field.

How can I fix this and leave it as the second image?

![modal](https://user-images.githubusercontent.com/22008303/39707974-3b2b03f0-51ec-11e8-95cd-716ec70851a1.png)

![google](https://user-images.githubusercontent.com/22008303/39707917-156c3e36-51ec-11e8-891e-fc96a7c43b67.png)

**Comment by JaconsMorais** [comment]
did you found a resolution for this issue?

**Comment by JaconsMorais** [comment]
Look, if you add .form-float into div, he will add an event click to the .form-control .form-float and .form-label classes, when the click event triggers, he will trigger an focus event in input elements inside the element triggered, and when the input element focus event trigger, he will add a class "focused" to elements that contain .form-line, after that, the label will be elevated.

To do that, you need to run $.AdminBSB.input.activate() AFTER the html componentes are loaded.

So, look if you are loading the admin.js(or another name) in the end of file, or, if you are adding html componentes dynamically, you need to run the method mentioned earlier after html loads.

**Comment by wagnerfillio** [comment]
OK thank you!

**Comment by acmr93** [comment]
> Look, if you add .form-float into div, he will add an event click to the .form-control .form-float and .form-label classes, when the click event triggers, he will trigger an focus event in input elements inside the element triggered, and when the input element focus event trigger, he will add a class "focused" to elements that contain .form-line, after that, the label will be elevated.
> 
> To do that, you need to run $.AdminBSB.input.activate() AFTER the html componentes are loaded.
> 
> So, look if you are loading the admin.js(or another name) in the end of file, or, if you are adding html componentes dynamically, you need to run the method mentioned earlier after html loads.

Ty
