### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zarulizham** [gurayyarar/AdminBSBMaterialDesign#13]
How to set initial theme color? First open is Red.

**Comment by gurayyarar** [comment]
Hi,
You can change the class name inside the `body`. Default theme class name is **theme-red**, so first open red

You can use these theme classes for change the color
- theme-red
- theme-pink
- theme-purple
- theme-deep-purple
- theme-indigo
- theme-blue
- theme-light-blue
- theme-cyan
- theme-teal
- theme-green
- theme-light-green
- theme-lime
- theme-yellow
- theme-amber
- theme-orange
- theme-deep-orange
- theme-brown
- theme-grey
- theme-blue-grey
- theme-black

Thanks
