### ISSUE TITLE
Appears to be an issue with the scrolling in the left pane

### ISSUE THREAD

**Issue by davidshieldsaz** [gurayyarar/AdminBSBMaterialDesign#131]
When I view the template from my android device, the left pane menu scrolls very slowly.  It takes a few swipes down to get the menu to move an inch.  Does anyone have a fix for this?

**Comment by LucaDiba** [comment]
It seems to be a [slimScroll bug](https://github.com/rochal/jQuery-slimScroll/issues/132).
I solved by removing that plugin and changing menu's height in `style.css`:
```
.sidebar .menu{
    /* From:
     * height: 90vh;
     * to:
     */
    height: calc(100vh - 70px - 135px);
}
```
Where:
- `70px` is `navbar` height
- `135px` is `user-info` height
