### ISSUE TITLE
Page not loading completely sometimes in laravel

### ISSUE THREAD

**Issue by akshay-kapase** [gurayyarar/AdminBSBMaterialDesign#135]
Hi, 
Im using this theme in laravel. But im facing one issue that the page does not load completely sometimes.
Is there anything that i can do to resolve this issue ?

**Comment by dheroefic** [comment]
Hello,

Are you sure it's not related to the network or your scripts? Our web apps are already deployed on the production server and there's no such issue so far in our test case. Btw we're using Laravel 5.6. Your best bet is chrome's devtools, inspect all element and the source is loaded or not. or it might be related to your script have an error or not (which console is really helpful to that).

**Comment by akshay-kapase** [comment]
OK thanks for the reply
