### ISSUE TITLE
Error displaying the Check Box

### ISSUE THREAD

**Issue by wagnerfillio** [gurayyarar/AdminBSBMaterialDesign#143]
My friend, there is something wrong with displaying the check box.

If you use only `<input type = "checkbox">` nothing appears.

Any solution?
Incompatible with bootstrap table plugin checkbox

**Comment by jefferyleo** [comment]
Same goes to me, the checkbox isn't appear in my bootgrid table, even I've write the same code as the example in adminbsb checkbox

**Comment by mattLLVW** [comment]
you need `materialize.css` available in your html.
