### ISSUE TITLE
Date/Time picker Not available like adminLTE

### ISSUE THREAD

**Issue by arunandroapps** [gurayyarar/AdminBSBMaterialDesign#150]
Hello,

Date/Time Picker plugin is also not supporting in this template, please provide supportable plugin for date time picker like aminLTE

![screen shot 2018-10-19 at 3 04 55 pm](https://user-images.githubusercontent.com/22675494/47210378-69f26c00-d3b0-11e8-85b5-370ba0548bc1.png)

**Comment by gurayyarar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/k3gBfpXl/1-test)

**Comment by gurayyarar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Date/Time picker Not available like adminLTE #150](https://trello.com/c/xcbQTCit/2-date-time-picker-not-available-like-adminlte-150)

**Comment by arunandroapps** [comment]
Thank You So Much For Reply, Waiting For Update
