### ISSUE TITLE
add show row length in exportable datatable

### ISSUE THREAD

**Issue by isanjaymaurya** [gurayyarar/AdminBSBMaterialDesign#157]
https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/tables/jquery-datatable.html

how to **show rows (10, 50, 100, 500)** in the exportable data-table.
i had use this server side datatable in the one of my project and show rows required in that datatable. i had added. here is what i had try. but its working in other project which have datatable v 1.10.16. (this code work with my other project in which i haven't use adminBSB theme)

any suggestion would be appreciated.

lengthMenu: [
--
  | [ 10, 25, 50, 100, 500, -1 ],
  | [ '10 rows', '25 rows', '50 rows', '100 rows', '500 rows', 'Show all' ]
  | ],
  | buttons: [
  | {
  | extend: 'colvis',
  | text: "Columns"
  | },
  | {
  | extend: 'pageLength',
  | text: 'Show'
  | },

------------or----------

$('#datatable1').dataTable({
--
  | dom: 'Bfrtip',
  | aaSorting : [[0, 'desc']],
  | lengthMenu: [
  | [ 10, 25, 50, 100, 500, -1 ],
  | [ '10 rows', '25 rows', '50 rows', '100 rows', '500 rows', 'Show all' ]
  | ],
  | buttons: [
  | 'pageLength'
  | ],
  | });

**Comment by kerim878** [comment]
This isn't issue of template. Please don't open issue unrelated to template. You can get help from Google or   [DataTables](http://datatables.net) official documentation. Please close issue if you can.

**Comment by isanjaymaurya** [comment]
yes but i dont have access to close this. and yes i got the solution we have to add 
dom: '1Bfrtip',
