### ISSUE TITLE
Sidebar Collapse - Question

### ISSUE THREAD

**Issue by gokulnaathrv** [gurayyarar/AdminBSBMaterialDesign#16]
Hi,

Is it possible to collapse the left hand menu side bar?

**Comment by gurayyarar** [comment]
Hi,
Sure, for the first load please follow these instructions;

**1)** We add `ls-closed` class to page `body` tag
![image](https://cloud.githubusercontent.com/assets/8344559/22541735/d4426dc4-e930-11e6-90ba-9aebeb385ceb.png)

**2)** _js -> admin.js_, delete or make comment these codes.
![image](https://cloud.githubusercontent.com/assets/8344559/22541756/fbfc927c-e930-11e6-8c2e-87191c61e1d9.png)

**3)** _css -> style.css_ adding **!important** code
![image](https://cloud.githubusercontent.com/assets/8344559/22541785/2d051c5e-e931-11e6-8604-8abc97bd489f.png)

**Comment by gokulnaathrv** [comment]
Thanks Mate. Worked like a charm !!

**Comment by harialby** [comment]
Hi,
$ not defined error when applying this theme.anyone plz tell the solution i cant use any jquery javascript functions .i am stuck in my project

**Comment by gudangcoding** [comment]
thx mate this work!
