### ISSUE TITLE
Supporting older ie versions(ie8 and ie9)

### ISSUE THREAD

**Issue by aren13** [gurayyarar/AdminBSBMaterialDesign#18]
Firstly, Thanks for this amazing theme.

Do you have any suggestions for how to support older ie versions ?

**Comment by gurayyarar** [comment]
Thanks for your feedback,
For you, it will be hard, because you need to change icon pack, lots of plugins you need change with older version, etc. So you should be use another themes for your project for support older ie version

Thanks
