### ISSUE TITLE
Refused to load the image

### ISSUE THREAD

**Issue by Bruno-Marley** [gurayyarar/AdminBSBMaterialDesign#190]
I'am trying to use an external image URL in the dashboard but when it loads the site the image don't load and appears that followed error on console:

Refused to load the image 'IMAGE_URL' because it violates the following Content Security Policy directive: "img-src 'self' data:".

How can I remove this?

**Comment by shubhamsish** [comment]
you can use alt

**Comment by Bruno-Marley** [comment]
I resolve in other way.
