### ISSUE TITLE
question about format

### ISSUE THREAD

**Issue by daniel180211** [gurayyarar/AdminBSBMaterialDesign#2]
form basic->datetime picker
after I selected the date, it shows date with names.
how can I do to get only date as datetime format(I mean Y-m-d)?

your work it's amazing!
thanks!

**Comment by gurayyarar** [comment]
Hi daniel180211,
Thanks for your kind opinion and comment about it. 

Please open the file, js/pages/forms/basic-form-elements.js and change like this, line 12-17

`    $('.datepicker').bootstrapMaterialDatePicker({
        format: 'YYYY-MM-DD',
        clearButton: true,
        weekStart: 1,
        time: false
    });`

We changed only **format option** as **YYYY-MM-DD**
For the other formats, you can check the moment.js plugin which webpage link is [http://momentjs.com/](http://momentjs.com/)

Thanks

**Comment by daniel180211** [comment]
a lot of thanks. it worked!

**Comment by gurayyarar** [comment]
You're welcome, have a nice work
