### ISSUE TITLE
Problem with progressbar and smartresize functions

### ISSUE THREAD

**Issue by ManuelEsp** [gurayyarar/AdminBSBMaterialDesign#20]
Hello. I'm tring to put my code into the template but when I try to load the page I get the following errors: 

![image](https://cloud.githubusercontent.com/assets/24298023/22843632/3760176a-efb9-11e6-9414-6a7c9aa49e57.png)

Any help is appreciated. Thank you!

**Comment by dodo2525** [comment]
You need to add admin.js & demo.js
It seems that you also forget to includes other .js files
