### ISSUE TITLE
Slow sidebar scroll on mobile(chrome)

### ISSUE THREAD

**Issue by rajabilal555** [gurayyarar/AdminBSBMaterialDesign#21]
In the sidebar , scrolling is a little bit hard, as it does not slide meaning it does not scroll right on swipes...
And is kinda slow...
Same with right bar with skin options...
And the side bar is sometimes a little too small on small screens ,maybe because of the footer in sidebar...

**Comment by n6ither** [comment]
I agree. The footer should be in the bottom oficina the entire page, not inside the sidebar.

**Comment by dodo2525** [comment]
It can be configurer with the Slimscroll Plugin
