### ISSUE TITLE
Profile menu style

### ISSUE THREAD

**Issue by n6ither** [gurayyarar/AdminBSBMaterialDesign#22]
Hello. First of all, let me congratulate you for this awesome template! A truly material design.

Now, can you help me please to change the profile menu to be more like this [one](http://byrushan.com/projects/ma/1-5-2/angular/#/home)? I'm talking about the submenu inside the same sidebar. I think it's fits better with the entire sidebar design.

Thank you.

PD: of course I will refer to you in my project, you did an excellent job!

**Comment by n6ither** [comment]
Hello?

**Comment by gurayyarar** [comment]
Hi,
Thanks for your kind opinions. We care of [Google Guidelines also their website](https://material.io/guidelines/), so we decided to make like this.
Your question didn't contain any issue.

Thanks
