### ISSUE TITLE
Sub menu is not auto focused

### ISSUE THREAD

**Issue by lawrencebenito** [gurayyarar/AdminBSBMaterialDesign#24]
I know this is just a small design issue but it is really important with the UX becuase some sub menu is not shown automatically (auto focus?) that the other user who clicked the + button might think there is no sub level. they have to scroll it manually. 

If the level 0 menu is at the bottom of the side bar and was clicked, the UI looks normal and fit to the side bar which causes the user to think that there is no sub level but actually there is. 

![selection_065](https://cloud.githubusercontent.com/assets/23550939/23089262/15acedba-f5c1-11e6-9a7f-ca972113e753.png)
![selection_066](https://cloud.githubusercontent.com/assets/23550939/23089263/16594a88-f5c1-11e6-91a2-6d54f4e32068.png)

**Comment by gurayyarar** [comment]
Hi,
I will publish new update, i will made this task

**Comment by lawrencebenito** [comment]
Wow, Thanks :) I am using using your template in our Capstone. Thanks a
lot. Your template is really great, :)

**Comment by lawrencebenito** [comment]
I just downloaded and check the new version. The version of the demo is still on 1.0.4 . This issues is not yet solve based on what I downloaded in the code tab here in github.

**Comment by gurayyarar** [comment]
Hi, please download as .zip file (like on screenshot).
![image](https://cloud.githubusercontent.com/assets/8344559/23927347/d9d404d0-0921-11e7-8ee1-58a7700a105d.png)

I will update npm and bower servers

**Comment by lawrencebenito** [comment]
haha yeah. That's what I did :) I redownload the zip just now with a
different pc still same issue :(
