### ISSUE TITLE
md-preloader does not work on IE10+

### ISSUE THREAD

**Issue by gsalvi** [gurayyarar/AdminBSBMaterialDesign#3]
Hi Güray,
I am a newbie in web development and found your project amazingly interesting. Definitely my kind of style. Thanks a lot!
Till now everything works well, but I have a problem with your preloaders. They do not work (even not on your official demo page) on IE10+ (nor Edge). More precisely, the animations do not work. 
Could you help me out? Would be very appreciated. 

Keep on doing such nice work! 

Giovanni

**Comment by arikurniawans** [comment]
![image](https://cloud.githubusercontent.com/assets/12132198/20658202/b15cffaa-b56d-11e6-96bd-3fe1ef3a6689.png)

**Comment by arikurniawans** [comment]
Hi mr. guray, this bug on template boostrap AdminBSB, why this happen

**Comment by gurayyarar** [comment]
Which browser and version you are using? Font libraries not loaded, it must be a old version of browsers.

**Comment by alirizaadiyahsi** [comment]
I think, it is not about browser version. I have same issue. When I test it in asp.net core project, everything is ok. But when I try to test it in a asp.net mvc5 project, it does not work. Same browser, different project types, different results.

**Comment by gurayyarar** [comment]
Could you publish the MVC 5 project and give me a link for check? I think, doesn't matter project types, because we talking about the Front End codes.

**Comment by alirizaadiyahsi** [comment]
You are right, it is not about project type, but I think there is a point that I missed out about loading font libraries. There is no console error message. If I find the problem, I will write it here.

I can't publish my project now.

**Comment by gurayyarar** [comment]
Ok, we pleasure the know after you inform the problem

Thank you and have a nice works

**Comment by alirizaadiyahsi** [comment]
I found it. It is very silly mistake :)

I forgot to refrence material icons (following lines)

    
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

I've tried to fix it for hours...

**Comment by alirizaadiyahsi** [comment]
Also, thank you very much for this amazing template...

**Comment by gurayyarar** [comment]
:) I glad to you solved the problem. And thank you for your kind opinion. The next errors please don't hesitate to write to us
