### ISSUE TITLE
jquery $ not defined error

### ISSUE THREAD

**Issue by harialby** [gurayyarar/AdminBSBMaterialDesign#30]
Hi,
i am using bsb material admin theme for my project.design is working fine.but i got error $ not defined when using jquery and javascript functions. so i cant use any jquery functions when theme is applying .please help to solve this.
thanks in advance.

**Comment by gurayyarar** [comment]
Hi,
I need more information about this, i didn't understand because the theme already built with jQuery v1 and did not test with jQuery version 2 and 3. Maybe you can send console screenshot, some codes etc...

**Comment by burakdobur** [comment]
Check your HTML, it sounds like jQuery library is added to the page more than one.

**Comment by harialby** [comment]
thank you for all solutions.the problem solved,the error shows the meaning of $ is overridden, solved it by declaring $(jquery)
