### ISSUE TITLE
<select> not rendering well

### ISSUE THREAD

**Issue by Woorales** [gurayyarar/AdminBSBMaterialDesign#33]
The select is not redereing as expected, with this code
 ```
<select class="form-control show-tick" tabindex="-98">
<option value="">-- Please select --</option>
<option value="10">10</option>
<option value="20">20</option>
<option value="30">30</option>
<option value="40">40</option>
<option value="50">50</option>
</select>
 ```

This is what is shown (the same happens with the datatables select for number of results per page), any idea why? i am missing something?

![1](https://cloud.githubusercontent.com/assets/629179/23869575/11ed13dc-07e9-11e7-9517-8949dba52c52.png)

**Comment by burakdobur** [comment]
I think you need to add bootstrap-select plugin's CSS to your html. I did that mistake too :) It's in the plugins folder.

**Comment by Woorales** [comment]
That solve the issue, thank you!!

**Comment by harialby** [comment]
i too have this issue.But i am binding dropdown on change javascript and its not showing correctly i already referred select css in view page .
This is what its shown.

![capture](https://cloud.githubusercontent.com/assets/26052967/24054038/deb7c428-0b60-11e7-9c0e-01093cb3c111.PNG)
 any idea what is missing.Thanks in advance.

**Comment by burakdobur** [comment]
Can't tell from this screenshot. Maybe other CSS rules are affecting your select. Or maybe it is the container issue, since it is too narrow to render. Can you try this:
```
   <select class="selectpicker" data-container="body">
  </select>
```
