### ISSUE TITLE
Dropdown not binding on change function

### ISSUE THREAD

**Issue by harialby** [gurayyarar/AdminBSBMaterialDesign#34]
I have a dropdown that binds when changing another dropdown's selection.The problem is that ,the dropdown options are not showing.When iam not applying theme on that page it works fine.I inspects with browser and can see all options are bind under` [ <select><option> ]`
but its not showing in dropdown.Below is my code:
javascript

![2017-03-16](https://cloud.githubusercontent.com/assets/26052967/24032143/7b21b8fa-0b0c-11e7-93a9-b02910bfc0fd.png)

.cshtml

![2017-03-](https://cloud.githubusercontent.com/assets/26052967/24032151/7f3b42a8-0b0c-11e7-8020-516b00a05dd7.png)

I am stuck with this.Anyone please help.Thanks in advance

**Comment by gurayyarar** [comment]
Hi,
Which page you saw this error. Because i need to know which plugin you are used for dropdown, and then i will check the events of the plugin on them website

**Comment by harialby** [comment]
i used the theme in my layout and refer that page as my master page in other view.i used select plugin and class as <form-control show tick>and its not binding to dropdown.i tried without using select plugin and its also not working.But  when i bind data on load itself from viewbag its showing as fine.only on change javascript is not working

**Comment by harialby** [comment]
![deb7c428-0b60-11e7-9c0e-01093cb3c111](https://cloud.githubusercontent.com/assets/26052967/24181980/70cface6-0ee4-11e7-90ad-5fe766a50d93.PNG)


this is what its shown when appending the dropdown using class name.and not showing any list when appending options normally

**Comment by REscobar** [comment]
Add `$('#drpSheets').selectpicker('refresh')` after adding all the elements
See: 
https://silviomoreto.github.io/bootstrap-select/methods/#selectpickerrefresh
