### ISSUE TITLE
Active not beign set on menus

### ISSUE THREAD

**Issue by William-H-M** [gurayyarar/AdminBSBMaterialDesign#36]
Hi, first that all thanks for such amazing template, not sure if this fall as an usage issue, but I'm having the following problem:

Using the menu doesn't set the class 'active' for menu `<li>` and for the `<li><a>` not sure why doesn't work like on the demo page, tried to find where you do it but didn't find it.
Image attached to see the problem:
![captura de pantalla 1](https://cloud.githubusercontent.com/assets/24443241/24474529/850f52c0-1492-11e7-8ec8-e5b6e3b17525.png)

I'm currently using ASP MVC 5
the href property looks fine too.
Do anyone else has a problem with or have a workaround?
Any help would be appreciate it

**Comment by REscobar** [comment]
The theme will not handle the menu/sidebar state, this has to be managed by you, with the `active` class on the `<li>` item.

If all your vies are only accesible by your sidebar menu, you may try to match the action url with the href property of your anchor (`<a>` tag) and set the `active` class

**Comment by gurayyarar** [comment]
Yes you need to handle by yourself as @REscobar said
