### ISSUE TITLE
Change Wizard color

### ISSUE THREAD

**Issue by FelixINX** [gurayyarar/AdminBSBMaterialDesign#39]
Hello!

When building a [wizard](https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/forms/form-wizard.html), I cannot change the color of the tabs and buttons.

Maybe a JS configuration option would be nice. For example :
```
    //Advanced form with validation
    var form = $('#wizard').show();
    form.steps({
        ...
        onInit: function (event, currentIndex) {
            ...

            // set wizard color to material blue
            setWizardColor('bg-blue');

            ...
        },
       ...
    });
```

In the meantime, what can I do?

Thanks!

**Comment by gurayyarar** [comment]
You can change with css codes now, but we will add this functionality to our theme,
Thanks
