### ISSUE TITLE
Jquery Datatables header overlap

### ISSUE THREAD

**Issue by adhesukmana** [gurayyarar/AdminBSBMaterialDesign#42]
it happened when i resized my web browser. but it didnt happened for normal table.
![datatables](https://cloud.githubusercontent.com/assets/27278180/24902999/3bf526c0-1ed6-11e7-9481-b3f0237b7c5b.png)

**Comment by Adohk** [comment]
You could add the datatables scroll so it keeps itself contained, here's mine:

```
//Exportable table
    $('.js-exportable').DataTable({
        bAutoWidth: false,
        scrollY: "900px",
        scrollX: true,
        scrollCollapse: true,
        processing: true,
        deferRender: true,
        dom: 'Bfrtlip',
        responsive: true,
        buttons: [
            'csv', 'excel', 'pdf'
        ]
    });
```

It has a problem when resizing to a higher resolution though, the column headers don't update properly.

**Comment by Adohk** [comment]
You can use a scroll collapse and a custom css to prevent overflow, here's my .js:
```JS
    $('.js-exportable').DataTable({
        "bAutoWidth": false,
        //"sScrollY": "100%",
        //"sScrollX": "100%",
        "bScrollCollapse": true,
        "bProcessing": true,
        deferRender: true,
        dom: 'Bfrtlip',
        "responsive": true,
        buttons: [
            'csv', 'excel', 'pdf'
        ]
    });

    $('.js-exportable').wrap('<div class="dataTables_scroll" />');
```

And on a custom css:
```CSS
.dataTables_scroll{
    overflow:auto;
    position:relative;
}
```

**Comment by pandyandi** [comment]
you can add div class "table responsive" before table start

http://stackoverflow.com/questions/26500010/responsive-bootstrap-datatable-not-collapsing-columns-at-the-correct-point
