### ISSUE TITLE
Text fileds with value and Floating Label focused

### ISSUE THREAD

**Issue by danielsystems** [gurayyarar/AdminBSBMaterialDesign#46]
Hi, first of all, thanks for this awesome template, Not sure if this behavior is an issue.
 
![image](https://cloud.githubusercontent.com/assets/26946967/25041347/0f8d5336-20d5-11e7-992f-15f30d4baa07.png)

This is from the demo (latest release), text fields with value and floating labels their parent (`form-line`) keeps holding the class `focused` on focusout, so the thing is that its behavior should be the same that text fields with value and NO floating label where their parents (`form-line`) only keeps holding the class `focused` when the field is on focus, and on focusout the class `focused` is removed.

That's it, and again thanks for the great template.
PD: Sorry if my english has grammar errors, i'm Spanish speaker, thanks!

**Comment by gurayyarar** [comment]
Hi,
Thanks for your opinion. It's not an issue, we coded like this for floating label examples.
