### ISSUE TITLE
RightSideBar Scroller doesn't load on first load.

### ISSUE THREAD

**Issue by Adohk** [gurayyarar/AdminBSBMaterialDesign#47]
This happened to me on Firefox and chrome, when the page is ready and you open the skin/options bar, the scroll-bar is not there and the menus height is limited.

http://i.imgur.com/TD4DMYA.gif

I solved it in the meantime by initializing the scroll bar functions on clicking the RightSideBar's toggle.

**Comment by gurayyarar** [comment]
Hi,
It's fixed. You can check which file you need to update here #45
