### ISSUE TITLE
question about mouse hover

### ISSUE THREAD

**Issue by Youlow** [gurayyarar/AdminBSBMaterialDesign#5]
Hello,
first of all i wanna say it's an amazing template!

Is it possible to make a selection of main menu items on mouseover?

Thanks for your job!

**Comment by gurayyarar** [comment]
Hello,
Thanks for your kind opinion about it. 

Which menu you are talking about? Top or left menu?

Thanks

-----Orijinal ileti-----
Kimden: "Youlow" <notifications@github.com>
Gönderme tarihi: ‎23.‎11.‎2016 04:16
Kime: "gurayyarar/AdminBSBMaterialDesign" <AdminBSBMaterialDesign@noreply.github.com>
Konu: [gurayyarar/AdminBSBMaterialDesign] question about mouse hover (#5)

Hello,
first of all i wanna say it's an amazing template!
Is it possible to make a selection of main menu items on mouseover?
Thanks for your job!

**Comment by Youlow** [comment]
Left menu - Home, Typography, etc.

**Comment by gurayyarar** [comment]
Hi, we have no future getting this functionality
Thanks
