### ISSUE TITLE
Mobile Resolution Compatibility 

### ISSUE THREAD

**Issue by rajabilal555** [gurayyarar/AdminBSBMaterialDesign#50]
I don't know why but I don't like those wide border/margins around those Cards in the Image... that gives a congested feeling, to the content of the card... 
![screenshot_2017-04-23-21-50-56-38](https://cloud.githubusercontent.com/assets/15360941/25315534/ea8c779a-286f-11e7-90fe-a19690c02552.png)

**Comment by Marzuki5** [comment]
just delete it by yourself guys :D

**Comment by smartclash** [comment]
Well, you can remove the border by yourself using CSS @rajabilal555 

You can see my mock-up code here

```css
.class-name {
    border: none !important;
}
```

**Comment by gurayyarar** [comment]
+1 @Marzuki5
