### ISSUE TITLE
Dinamic Select Box With Jquery is Conflict

### ISSUE THREAD

**Issue by irvan25** [gurayyarar/AdminBSBMaterialDesign#51]
I tried to make the select box dynamic, but it did not work, then I deleted the code $ .AdminBSB.input in admin.js. And the dynamic select box works.

**Comment by gurayyarar** [comment]
Do you have any screenshot, code samples or etc for understanding issue?

**Comment by mnborana** [comment]
need solution for this 
dynamic select not working

**Comment by maurosanz22** [comment]
Hi, any solution for this?

**Comment by gurayyarar** [comment]
@irvan25 I'm closing this issue. If you have still same issue, please reopen
