### ISSUE TITLE
Map Project Plugin Dependencies in Bower

### ISSUE THREAD

**Issue by mateusmanuel** [gurayyarar/AdminBSBMaterialDesign#53]
In the Bower file you have put only the final project. I think that is interesting to place the plugins to manage the versions. I think that I can do this.

**Comment by gurayyarar** [comment]
Hi,
If you want to you can download old version like this;

`bower install adminbsb-materialdesign@1.0.4`

Now, the latest version is 1.0.5

**Comment by graterolz** [comment]
Hi, That version has the bower dependecies details?

**Comment by gurayyarar** [comment]
Totally right
