### ISSUE TITLE
form-float bug with modal

### ISSUE THREAD

**Issue by klinux** [gurayyarar/AdminBSBMaterialDesign#54]
form-float don't work with modal.

If I create a form within modal, the floating form float don't go to the top

Thank you

**Comment by gurayyarar** [comment]
Do you have any code sample, screenshot or etc for understanding issue?

**Comment by klinux** [comment]
Hello gurayyarar,

The problem is that modal is loaded after admin.js, I need to fix this, thank you for the response.

Ps.: I make a donate to you, thank you, you done a great job.

**Comment by gurayyarar** [comment]
Hi,
Thanks for your donation and kind opinion.

I tested but i couldn't see any error;
![forgithub](https://user-images.githubusercontent.com/8344559/27583614-a11b1660-5b3d-11e7-8803-004b72dd7149.gif)

I used this codes for modal
```
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control">
                        <label class="form-label">Username</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>

    </div>
</div>
```

**Comment by klinux** [comment]
The problem is in my system, the modal is loaded dynamically, and it is loaded after admin.js, the modal it's not in the page, and this cause problems, but I is only in my system here, I tried in the same way that you, everything works fine.

**Comment by acmr93** [comment]
could you solve it?
