### ISSUE TITLE
text not equal with icon in button

### ISSUE THREAD

**Issue by pandyandi** [gurayyarar/AdminBSBMaterialDesign#55]
i want to use button with icon and text but position of them is not equal. how to fix it?
![whatsapp image 2017-05-24 at 19 45 40](https://cloud.githubusercontent.com/assets/26289723/26403854/f3e016aa-40b9-11e7-9c12-901024cfa96f.jpeg)

i want to use button like this
![whatsapp image 2017-05-24 at 19 49 34](https://cloud.githubusercontent.com/assets/26289723/26403898/252c4864-40ba-11e7-929f-43e07269c1cb.jpeg)

**Comment by gurayyarar** [comment]
Hi,
We added this functionality to theme.

Release version has been published now which page link is **[Version 1.0.5](https://github.com/gurayyarar/AdminBSBMaterialDesign/releases/tag/v1.0.5)**

**[DEMO PAGE](https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/ui/buttons.html)** 
Title of *ICON & TEXT BUTTONS*

Please follow these instructions;
**1)** Update your **css/style.css** & **css/style.min.css**
**2)** Add button text inside a *span* element

**Code Sample:**
```
<button type="button" class="btn btn-success waves-effect">
    <i class="material-icons">home</i>
    <span>HOME</span>
</button>
```

Thanks for your supporting @pandyandi

**Comment by pandyandi** [comment]
Yes, thank you very much @gurayyarar

**Comment by gurayyarar** [comment]
@pandyandi You are welcome, i hope working also for you :)
