### ISSUE TITLE
Sidebar with internet explorer

### ISSUE THREAD

**Issue by physio** [gurayyarar/AdminBSBMaterialDesign#58]
the sidebar with internet explorer (all versions) it is broke and impossibile to use. can you help me please?
I must to open compatibility and disable the flag. 
Why the  meta http-equiv="X-UA-Compatible" content="IE=EDGE"  don't force the browser?

**Comment by gurayyarar** [comment]
Hi,
Could you send a screenshot and more info for see the error?

_(**Note:** This theme compatible with IE10 and up versions & IE Edge. I tested for these versions.)_
