### ISSUE TITLE
Used this theme in a free ASP.NET Core & Angular startup project

### ISSUE THREAD

**Issue by hikalkan** [gurayyarar/AdminBSBMaterialDesign#62]
I just wanted to inform everyone looking for an adaptation of this theme for ASP.NET Core & Angular. I have just released a startup project based on this: https://github.com/aspnetboilerplate/module-zero-core-template

Thank you @gurayyarar for your wonderful work!

**Comment by gurayyarar** [comment]
Thanks for your supporting and kind opinion,
If you need a help, please don't hesitate the contact with me

Thanks again @hikalkan

**Comment by ryc16** [comment]
Thank you both for the wonderful work.  I like the full demo page. https://gurayyarar.github.io/AdminBSBMaterialDesign/index.html

@gurayyarar, is this possible to have same demo page using your framework "ASP.NET Core & Angular". I tried to use some features mentioned from AdminBSB ie. datetimepicker but I got some difficulty to get it work on the "ASP.NET Core & Angular" project.
