### ISSUE TITLE
.input-group with right addon and error label not working properly

### ISSUE THREAD

**Issue by morrisjdev** [gurayyarar/AdminBSBMaterialDesign#63]
When using the .input-group and an addon at the right side a label will not get formatted properly.

```
<div class="input-group">
    <span class="input-group-addon">
        ...
    </span>

    <div class="form-line">
        <input type="text" class="form-control">
    </div>

    <span class="input-group-addon">
        ...
    </span>

    <label class="error">
        error
    </label>
</div>
```

Fixed it by putting `<label>` into a `<div>` with `display: table-row;`.

Maybe you could include this fix into the project and provide a demo with addon and error validation.

**Comment by gurayyarar** [comment]
Hi,
Could you send the full code for understanding issue?

Thanks

**Comment by gurayyarar** [comment]
@morrisjdev If you have still same issue, please reopen.
