### ISSUE TITLE
Responsive bug on  iPad 

### ISSUE THREAD

**Issue by longhuynh** [gurayyarar/AdminBSBMaterialDesign#66]
![image](https://user-images.githubusercontent.com/5002046/27244876-34115f58-52ae-11e7-8622-35734609fdb3.png)

**Comment by gurayyarar** [comment]
Hi,
The donut chart not understanding the resize function. So when you resize the window, you need to refresh the page. Already, someone enter this demo with IPad, they will see like refresh the page like this;

![image](https://user-images.githubusercontent.com/8344559/27584479-df69f6d6-5b40-11e7-8f0c-8e3338048743.png)

Thanks
