### ISSUE TITLE
AdminBSB >> bootstrap-material-datetimepicker >> Year disabled >> Only left and right arrows work for navigation

### ISSUE THREAD

**Issue by ChetanTomar** [gurayyarar/AdminBSBMaterialDesign#67]
If I want to select 1997 I have to go through with multiple clicks. This is not correct behaviour of   `bootstrap-material-datetimepicker`  

**See this** [http://t00rk.github.io/bootstrap-material-datetimepicker](http://t00rk.github.io/bootstrap-material-datetimepicker). In first example here we can see that if we click on **`Year`** it shows **`list of years`** through which we can easily move to previous years.

**Comment by ChetanTomar** [comment]
@gurayyarar  Why closed?  In AdminBSB theme this is not working as expected.

**Comment by gurayyarar** [comment]
Because of it is not a issue, it can be only a suggestion
