### ISSUE TITLE
jquery does not work in footer

### ISSUE THREAD

**Issue by hamedmoody** [gurayyarar/AdminBSBMaterialDesign#68]
Hi
Jquery does not word in footer area.
"assets/js/pages/index.js" has problem.

**Comment by hamedmoody** [comment]
Hi
Jquery does not word in footer area.
"assets/js/pages/index.js" has problem.

**Comment by gurayyarar** [comment]
Hi,
What you mean "not work"? Is there any error code or something for understand your problem?

**Comment by hamedmoody** [comment]
i solve it by this change:
`if( $('.dashboard-flot-chart').length ) {
        initRealTimeChart();
    }
    if( $('.dashboard-donut-chart').length ) {
        initDonutChart();
    }
    initSparkline();`

**Comment by hamedmoody** [comment]
if not dashboard and not have donot chart and realtime chart then we can not change theme and if add jquery code before </body> does not work any code

**Comment by Ayhoum** [comment]
Would you please tell me what you did to solve the problem? .. where did you add that code?

**Comment by hamedmoody** [comment]
required scrip does not included in that document
