### ISSUE TITLE
Form wizard issue with select option

### ISSUE THREAD

**Issue by amolswnz** [gurayyarar/AdminBSBMaterialDesign#69]
While using select option inside form wizard, the currently selected item is not shown. For the following code, it always shows 1
```
<select name="days">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
</select>
```
If we use `<select class="form-control show-tick" data-live-search="true" name="days">`
we get the following error
```
bootstrap-select.js:1464 Uncaught TypeError: Cannot read property 'options' of undefined
    at HTMLInputElement.keydown (bootstrap-select.js:1464)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
keydown	@	bootstrap-select.js:1464
dispatch	@	jquery.min.js:3
r.handle	@	jquery.min.js:3
```

**Comment by gurayyarar** [comment]
Hi,
You can solve your problem with these instructions;
*(Note: Please click the images for actual sizes)*

**1)** *js -> admin.js* - Disable or remove this line
![image](https://user-images.githubusercontent.com/8344559/27585562-7c08d094-5b45-11e7-9234-0c93bf941753.png)

**2)** Write this code the Jquery Steps *onInit function*
`$.AdminBSB.select.activate();`

![image](https://user-images.githubusercontent.com/8344559/27585687-ed31e6e8-5b45-11e7-9865-06fab07dfdd1.png)

Thanks.
