### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by jamboljack** [gurayyarar/AdminBSBMaterialDesign#76]
Hai Gurayyarar, thanks for sharing this awesome template. 
Can you added a Profile Page ? 

Thanks again. :)

**Comment by gurayyarar** [comment]
Hi,
Thanks your kind opinion. I will, but not in short time.

**Comment by jamboljack** [comment]
Yap,, we all need that page. 
I will wait.... 
Thank You @gurayyarar ...

**Comment by sunnyg1210** [comment]
Not sure if it will help you guys but I have created a Angular 4 version in which I have added a profile page. It is available at https://github.com/sunnyg1210/adminbsbmaterial-ANGULAR

**Comment by gurayyarar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Profile Page #76](https://trello.com/c/AtpeNqEr/7-profile-page-76)
