### ISSUE TITLE
EXPORTABLE TABLE

### ISSUE THREAD

**Issue by joshuaayomikun** [gurayyarar/AdminBSBMaterialDesign#79]
i'm getting this error on my code 
![capture](https://user-images.githubusercontent.com/12767079/28956393-75e5081a-78e4-11e7-9095-a1d3c95b239b.JPG)

**Comment by gurayyarar** [comment]
Hi,
Please be sure these js files include with same order also, like this demo page which link is [https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/tables/jquery-datatable.html](https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/tables/jquery-datatable.html)

![image](https://user-images.githubusercontent.com/8344559/29762038-ee65bd0e-8bd4-11e7-81db-710fc30a0883.png)
