### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by Usman-Majeed** [gurayyarar/AdminBSBMaterialDesign#84]
Dear gurayyaar,

First of all thank you for such a great effort for development of a comprehensive bootstrap based admin template. But i have faced an issue in running the template demo in Microsoft Internet Explorer 11.

Demo web doesn't hide the loading screen, furthermore i have applied template on our web admin portal, there it doesn't show up glyphicons and bootstrap tabs.

Any help in this regard will be highly appreciated.
Thanks,
Usman Majeed.

**Comment by burakdobur** [comment]
I just tested in IE11, tabs and icons works fine. Can you check browser console and look for any error messages there?

**Comment by Usman-Majeed** [comment]
Dear burakdobur!
Thank you for your reply, i checked it and there was problem with our custom glyph icons creation, we re-created the glyph icons and it works fine in all browsers.
For the tabs visibility problem, there was a CSS property value issue, scaleX(0) was recognized by other browsers to show the tab, whereas IE was hiding the tab, setting scaleX(1) fixed the visibility problem of tabs for all browsers.
Issue is closed.
