### ISSUE TITLE
Left Sidebar can be minimized on the large screen size

### ISSUE THREAD

**Issue by guntursp** [gurayyarar/AdminBSBMaterialDesign#86]
Hi Gurayyarar,

Thank you for providing this awesome Admin Material Design template.
As per subject, I knew that the Left Sidebar can be minimized (toggled) if the screen size is small. But, can we add the 'hamburger' button on the wide/large screen as well, so it can toggled on the large screen size as well.

Thanks
-gs

**Comment by Adohk** [comment]
You can check #4

**Comment by guntursp** [comment]
Thank you @Adohk
