### ISSUE TITLE
Left Sidebar doesn't scroll to the current active item

### ISSUE THREAD

**Issue by Yousefjb** [gurayyarar/AdminBSBMaterialDesign#9]
If you are at [tabs](https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/ui/tabs.html) and want to go to [thumbnails](https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/ui/thumbnails.html) you have to scroll the whole list to reach it

**Comment by gurayyarar** [comment]
Hi,
Thanks for your helping. I will also add this functionality and publish the next update
